### ISSUE TITLE
MASP visuals on GitHub

### ISSUE THREAD

**Issue by awasunyin** [anomanetwork/masp#2]
Mini task:
1. Go to Settings of this repo
2. Social Preview --> pick an image from [this folder](https://drive.google.com/drive/u/1/folders/1rRvQ-TLgC7FYuX5r646JTmduy9l27_Kp).
3. Test this on e.g. Wire or Twitter (copy / paste the URL of this repo) and see how it looks like (take a screenshot)

**Comment by Asamartino** [comment]
As suggested, tested it [here](https://cards-dev.twitter.com/validator ). It looks like this: 
![test](https://user-images.githubusercontent.com/61462365/100355484-238d8380-2ff2-11eb-9da0-f0901eb4380d.png)

**Comment by ggkitsas** [comment]
@awasunyin @Asamartino is this task finished, shall I close the issue?
